# Generated by Django 5.0.7 on 2024-07-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentContent',
            new_name='content',
        ),
    ]
