# Generated by Django 5.0.7 on 2024-07-30 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_rename_commentcontent_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='Text',
        ),
    ]
